### ISSUE TITLE
リアルタイム危険検知スタートアップがシステムをオンプレからAWSへ移行した茨の道

### ISSUE THREAD

**Issue by junjunjunya** [aws-startup-community/aws-startup-community-conference-2022-cfp#20]
### AWS 行動規範 (Code of Conduct) への同意 (必須)

- [X] 私は、[AWS 行動規範 (Code of Conduct)](https://aws.amazon.com/jp/codeofconduct/) を確認し、同意しました

### Twitter ID (必須)

JunyaA0755

### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

フィットネスジム向けのリアルタイム危険検知ソリューション「**GYMDX**」は、サービスローンチから半年間は各施設にオンプレサーバーを配置し運用をしておりました。

しかし、施設が増えるごとにオンプレサーバーが増え、ハードウエアの故障対応や管理が非常に煩雑になるなど問題が頻発していた為、今後のサービスのスケールや拡張性を考えAWSを利用したクラウド化を行いました。

画像解析システムのクラウド化に際し、手間取った箇所・工夫した点やAWSのメリットデメリットに関してご共有させて頂ければと思います！

### 登壇者の所属するスタートアップのフェーズ （必須）

Seed

### 想定受講者のスタートアップのフェーズ (複数選択可) (必須)

series A, series B, series C, series D 以降

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

Web バックエンド / サーバーサイド開発, DevOps / Infrastructure as Code, 機械学習モデル開発

### セッションのトピック (複数選択可) (必須)

アプリケーションアーキテクチャー, 開発プロセス, その他

### セッションのフォーマット (必須)

スライドを映しながら話す、通常セッション

**Comment by kzk-maeda** [comment]
AWS Startup Community運営です。
Twitterでご連絡できなかったので、こちらから失礼します。

この度はAWS Startup Community Conference 2022のCFPにお申し込みいただきありがとうございました。
貴方のCFPをもとに選考を進めさせて頂きましたが、熟考いたしました結果
残念ながらご希望に添えない結果となりました。
 
枠に対して多数のご応募をいただいている中で、イベントのコンセプト上、より反響の大きいCFPや、よりスタートアップの課題にフォーカスしたCFPを採択する判断をさせていただきました。
何卒ご理解の程お願い申し上げます。

今後も様々なイベントを開催していく予定です。ご応募いただいた内容は非常に興味深く、次回以降のイベントなどで是非登壇のお申し込みをいただけることを楽しみにしております。

今後ともよろしくお願いします。
